[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Handle SPA routing (important for React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
